### ISSUE TITLE
Dots in sample ids

### ISSUE THREAD

**Issue by emilia2603** [maiasmith/mapscape#1]
Hi Maia,

Wonderful job on this beautiful package! I've been trying to use it to plot some of our multi-region data. What I noticed is that the package doesn't work when you have long sample ids with dots in them. ie. TTTT-XX-XX.R1. But it works once the sample id is shortened. ie. R1 Perhaps you could list this in the documentation?

Cheers,
Emilia

**Comment by maiasmith** [comment]
Hi Emilia,

Thanks so much for bringing this to my attention, and I'm so sorry about this bug! I hope it didn't take you too long to find! I will make changes asap - either to the documentation or code or both.

Best,
Maia

**Comment by maiasmith** [comment]
Hey Emilia,

I fixed the bug - now it will just convert the periods to underscores. The changes should appear in the release branch on the next bioc release, but are currently under the master branch. Thanks so much for bringing this to my attention! 

Best,
Maia
